[package]
name = "{YOUR_USERNAME}/my-game"
version = "0.1.4"
description = "This is my awesome game"
readme = "README.md"
repository = "https://github.com/..."

[[module]]
name = "game"
source = "game.wasm"
abi = "wasm4"
interfaces = { wasm4 = "0.0.1" }

[[command]]
runner = "wasm4@0.0.1"
name = "play"
module = "game"
